//layout with url logo
import { Inter } from 'next/font/google'
import './globals.css'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: '321Click',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Image
          src="https://321click.cl/wp-content/uploads/2017/04/click-transparente-chico.png"
          alt="321Click Logo"
          width={100}
          height={100}
        />
        {children}
      </body>
    </html>
  )
}
